language: python
# command to install dependencies
cache:
  - pip
install:
  - "pip install --upgrade pip; pip install --upgrade setuptools; pip install -r test_requirements.txt"
# command to run tests
matrix:
  include:
    - python: "2.7"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
script:
  - python tests/test_1.py
  - python tests/test_2.py
  - python tests/test_3.py
#  - nosetests $TESTCASE --with-coverage --cover-package=zappa --with-timer
#      - coverage combine --append
after_success:
  coveralls
