language: python
# command to install dependencies
cache:
  - pip
install:
  - "pip install --upgrade pip; pip install --upgrade setuptools; pip install -r test_requirements.txt"
# command to run tests
dist: trusty
#dist: xenial
matrix:
  include:
    - python: "2.7"
      env:
        - TESTCASE=tests/test_1.py
        - TESTCASE=tests/test_2.py
        - TESTCASE=tests/test_3.py
    - python: "3.6"
      env:
        - TESTCASE=tests/test_1.py
        - TESTCASE=tests/test_2.py
        - TESTCASE=tests/test_3.py
    - python: "3.7"
      env:
        - TESTCASE=tests/test_1.py
        - TESTCASE=tests/test_2.py
        - TESTCASE=tests/test_3.py
      dist: xenial
      sudo: true
script:
  - python $TESTCASE
#  - nosetests $TESTCASE --with-coverage --cover-package=zappa --with-timer
#      - coverage combine --append
after_success:
  coveralls
